package com.omondit.alarmfocus.domain.model

import android.os.Parcelable
import com.omondit.alarmfocus.utils.QuoteManager
import kotlinx.parcelize.Parcelize
import org.json.JSONObject

/**
 * Base mission interface for wake-up challenges
 */
abstract class Mission {
    abstract val type: MissionType
    abstract val difficulty: Difficulty
    abstract val config: MissionConfig

    abstract fun generateChallenge(): Challenge
    abstract fun validateAnswer(challenge: Challenge, answer: String): ValidationResult

    enum class MissionType {
        NONE, MATH, BARCODE, PHOTO, ACTIVITY, TYPING
    }

    enum class Difficulty(val displayName: String) {
        EASY("Easy"),
        MEDIUM("Medium"),
        HARD("Hard")
    }
}

/**
 * Mission configuration that can be serialized to JSON
 */
@Parcelize
data class MissionConfig(
    val type: Mission.MissionType = Mission.MissionType.NONE,
    val difficulty: Mission.Difficulty = Mission.Difficulty.EASY,
    val parameters: Map<String, String> = emptyMap()
) : Parcelable {

    fun toJson(): String {
        val json = JSONObject().apply {
            put("type", type.name)
            put("difficulty", difficulty.name)
            put("parameters", JSONObject(parameters))
        }
        return json.toString()
    }

    companion object {
        fun fromJson(jsonString: String): MissionConfig {
            return try {
                val json = JSONObject(jsonString)
                val type = Mission.MissionType.valueOf(json.optString("type", "NONE"))
                val difficulty = Mission.Difficulty.valueOf(json.optString("difficulty", "EASY"))
                val parametersJson = json.optJSONObject("parameters")

                val parameters = mutableMapOf<String, String>()
                parametersJson?.let { params ->
                    params.keys().forEach { key ->
                        parameters[key] = params.getString(key)
                    }
                }

                MissionConfig(type, difficulty, parameters)
            } catch (e: Exception) {
                MissionConfig() // Default config if parsing fails
            }
        }
    }
}

/**
 * Represents a challenge generated by a mission
 */
data class Challenge(
    val id: String,
    val question: String,
    val correctAnswer: String,
    val options: List<String>? = null, // For multiple choice questions
    val data: Map<String, Any> = emptyMap(), // Additional challenge data
    val timeoutSeconds: Int = 120,
    val allowedAttempts: Int = 3,
    val createdAt: Long = System.currentTimeMillis()
)

/**
 * Result of answer validation
 */
data class ValidationResult(
    val isCorrect: Boolean,
    val message: String,
    val shouldEscalate: Boolean = false, // Make next challenge harder
    val attemptsRemaining: Int = 0
)

/**
 * Mission completion result
 */
data class MissionResult(
    val success: Boolean,
    val completionTime: Long, // Time taken to complete in milliseconds
    val attempts: Int,
    val score: Float, // 0.0 to 1.0 based on performance
    val timestamp: Long = System.currentTimeMillis()
)

/**
 * Math mission implementation
 */
class MathMission(
    override val difficulty: Mission.Difficulty = Mission.Difficulty.EASY,
    override val config: MissionConfig = MissionConfig()
) : Mission() {

    override val type = MissionType.MATH

    companion object {
        private const val EASY_MAX_NUMBER = 50
        private const val MEDIUM_MAX_NUMBER = 100
        private const val HARD_MAX_NUMBER = 999
        private const val EASY_OPERATIONS = "+-"
        private const val MEDIUM_OPERATIONS = "+-*"
        private const val HARD_OPERATIONS = "+-*/"
    }

    override fun generateChallenge(): Challenge {
        val (num1, num2, operation) = when (difficulty) {
            Difficulty.EASY -> generateEasyProblem()
            Difficulty.MEDIUM -> generateMediumProblem()
            Difficulty.HARD -> generateHardProblem()
        }

        val question = "$num1 $operation $num2 = ?"
        val correctAnswer = calculateAnswer(num1, num2, operation).toString()

        return Challenge(
            id = generateChallengeId(),
            question = question,
            correctAnswer = correctAnswer,
            data = mapOf(
                "num1" to num1,
                "num2" to num2,
                "operation" to operation
            ),
            timeoutSeconds = when (difficulty) {
                Difficulty.EASY -> 60
                Difficulty.MEDIUM -> 90
                Difficulty.HARD -> 120
            }
        )
    }

    override fun validateAnswer(challenge: Challenge, answer: String): ValidationResult {
        val cleanAnswer = answer.trim()
        val correctAnswer = challenge.correctAnswer

        return if (cleanAnswer == correctAnswer) {
            ValidationResult(
                isCorrect = true,
                message = "Correct! Well done!",
                shouldEscalate = false
            )
        } else {
            ValidationResult(
                isCorrect = false,
                message = "Incorrect. The answer is $correctAnswer",
                shouldEscalate = true // Make next problem harder
            )
        }
    }

    private fun generateEasyProblem(): Triple<Int, Int, Char> {
        val operations = EASY_OPERATIONS.toCharArray()
        val operation = operations.random()

        return when (operation) {
            '+' -> {
                val num1 = (1..EASY_MAX_NUMBER).random()
                val num2 = (1..EASY_MAX_NUMBER).random()
                Triple(num1, num2, operation)
            }
            '-' -> {
                val num1 = (10..EASY_MAX_NUMBER).random()
                val num2 = (1..num1).random() // Ensure positive result
                Triple(num1, num2, operation)
            }
            else -> Triple(1, 1, '+') // Fallback
        }
    }

    private fun generateMediumProblem(): Triple<Int, Int, Char> {
        val operations = MEDIUM_OPERATIONS.toCharArray()
        val operation = operations.random()

        return when (operation) {
            '+' -> {
                val num1 = (10..MEDIUM_MAX_NUMBER).random()
                val num2 = (10..MEDIUM_MAX_NUMBER).random()
                Triple(num1, num2, operation)
            }
            '-' -> {
                val num1 = (20..MEDIUM_MAX_NUMBER).random()
                val num2 = (1..num1).random()
                Triple(num1, num2, operation)
            }
            '*' -> {
                val num1 = (2..12).random() // Keep multiplication manageable
                val num2 = (2..12).random()
                Triple(num1, num2, operation)
            }
            else -> Triple(5, 5, '+')
        }
    }

    private fun generateHardProblem(): Triple<Int, Int, Char> {
        val operations = HARD_OPERATIONS.toCharArray()
        val operation = operations.random()

        return when (operation) {
            '+' -> {
                val num1 = (100..HARD_MAX_NUMBER).random()
                val num2 = (100..HARD_MAX_NUMBER).random()
                Triple(num1, num2, operation)
            }
            '-' -> {
                val num1 = (200..HARD_MAX_NUMBER).random()
                val num2 = (1..num1).random()
                Triple(num1, num2, operation)
            }
            '*' -> {
                val num1 = (11..25).random()
                val num2 = (11..25).random()
                Triple(num1, num2, operation)
            }
            '/' -> {
                val num2 = (2..20).random()
                val result = (5..50).random()
                val num1 = num2 * result // Ensure clean division
                Triple(num1, num2, operation)
            }
            else -> Triple(10, 10, '+')
        }
    }

    private fun calculateAnswer(num1: Int, num2: Int, operation: Char): Int {
        return when (operation) {
            '+' -> num1 + num2
            '-' -> num1 - num2
            '*' -> num1 * num2
            '/' -> num1 / num2
            else -> 0
        }
    }

    private fun generateChallengeId(): String {
        return "math_${System.currentTimeMillis()}_${(1000..9999).random()}"
    }
}

/**
 * Mission factory for creating missions based on type and config
 */
object MissionFactory {

    fun createMission(config: MissionConfig, context: android.content.Context? = null): Mission {
        return when (config.type) {
            Mission.MissionType.MATH -> MathMission(config.difficulty, config)
            Mission.MissionType.BARCODE -> {
                val barcodeManager = context?.let { BarcodeManager(it) }
                val registeredBarcodes = barcodeManager?.getRegisteredBarcodes() ?: emptyList()
                BarcodeMission(config.difficulty, config, registeredBarcodes)
            }
            Mission.MissionType.PHOTO -> {
                val photoManager = context?.let { PhotoManager(it) }
                val registeredPhotos = photoManager?.getRegisteredPhotos() ?: emptyList()
                PhotoMission(config.difficulty, config, registeredPhotos)
            }
            Mission.MissionType.ACTIVITY -> ActivityMission(config.difficulty, config)
            Mission.MissionType.TYPING -> {
                val quoteManager = context?.let { QuoteManager(it) }
                TypingMission(config.difficulty, config, quoteManager)
            }
            Mission.MissionType.NONE -> NoMission()
        }
    }

    fun getDefaultConfig(type: Mission.MissionType): MissionConfig {
        return when (type) {
            Mission.MissionType.MATH -> MissionConfig(
                type = type,
                difficulty = Mission.Difficulty.EASY,
                parameters = mapOf(
                    "max_attempts" to "3",
                    "timeout_seconds" to "60"
                )
            )
            else -> MissionConfig(type = type)
        }
    }
}

/**
 * No-op mission for when missions are disabled
 */
class NoMission : Mission() {
    override val type = MissionType.NONE
    override val difficulty = Difficulty.EASY
    override val config = MissionConfig()

    override fun generateChallenge(): Challenge {
        return Challenge(
            id = "no_mission",
            question = "",
            correctAnswer = "",
            timeoutSeconds = 0,
            allowedAttempts = 0
        )
    }

    override fun validateAnswer(challenge: Challenge, answer: String): ValidationResult {
        return ValidationResult(
            isCorrect = true,
            message = "Mission disabled",
            shouldEscalate = false
        )
    }
}

/**
 * Mission state management for active challenges
 */
class MissionSession(
    val alarmId: Long,
    val mission: Mission,
    var currentChallenge: Challenge? = null,
    var attempts: Int = 0,
    var startTime: Long = System.currentTimeMillis(),
    var escalationLevel: Int = 0
) {

    fun generateNewChallenge(): Challenge {
        val challenge = mission.generateChallenge()
        currentChallenge = challenge
        attempts = 0
        return challenge
    }

    fun submitAnswer(answer: String): ValidationResult {
        val challenge = currentChallenge ?: return ValidationResult(
            isCorrect = false,
            message = "No active challenge"
        )

        attempts++
        val result = mission.validateAnswer(challenge, answer)

        if (result.shouldEscalate) {
            escalationLevel++
            // TODO: Implement escalation logic (increase difficulty)
        }

        return result.copy(
            attemptsRemaining = maxOf(0, challenge.allowedAttempts - attempts)
        )
    }

    fun isExpired(): Boolean {
        val challenge = currentChallenge ?: return false
        val elapsed = (System.currentTimeMillis() - startTime) / 1000
        return elapsed > challenge.timeoutSeconds
    }

    fun isMaxAttemptsReached(): Boolean {
        val challenge = currentChallenge ?: return false
        return attempts >= challenge.allowedAttempts
    }

    fun getCompletionResult(success: Boolean): MissionResult {
        val completionTime = System.currentTimeMillis() - startTime
        val score = if (success) {
            // Calculate score based on time and attempts
            val timeScore = maxOf(0f, 1f - (completionTime.toFloat() / (60 * 1000))) // Bonus for speed
            val attemptScore = maxOf(0f, 1f - (attempts.toFloat() / 3)) // Penalty for multiple attempts
            (timeScore + attemptScore) / 2f
        } else 0f

        return MissionResult(
            success = success,
            completionTime = completionTime,
            attempts = attempts,
            score = score.coerceIn(0f, 1f)
        )
    }
}
